name: base
channels:
  - <unknown>
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37h540881e_2
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - conda=22.9.0=py37h89c1867_1
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - cryptography=38.0.2=py37h5994e8b_1
  - cudatoolkit=11.2.2=hbe64b41_11
  - curl=7.86.0=hdc1c0ab_2
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dlenv-tf-2-9-gpu=1.0.20221215=py37h86df6ca_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - git=2.39.0=pl5321h693f4a3_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib_resources=5.10.1=pyhd8ed1ab_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - jupyter_server=1.23.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libcurl=7.86.0=hdc1c0ab_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuv=1.44.2=h166bdaf_0
  - libzlib=1.2.13=h166bdaf_4
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - nb_conda=2.2.1=unix_6
  - nb_conda_kernels=2.3.1=py37h89c1867_1
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbconvert=7.2.6=pyhd8ed1ab_0
  - nbconvert-core=7.2.6=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.6=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nodejs=18.12.1=h8839609_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - openssl=3.0.7=h0b41bf4_1
  - pandoc=2.19.2=h32600fe_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.3=py37h540881e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycosat=0.6.4=py37h540881e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37_1
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.7=3_cp37m
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - ruamel_yaml=0.15.100=py37h27cfd23_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h4ff8645_0
  - terminado=0.17.1=pyh41d4057_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py37h540881e_0
  - traitlets=5.7.1=pyhd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.18.0=py37h540881e_0
  - pip:
    - absl-py==1.3.0
    - affine==2.4.0
    - aiohttp==3.8.3
    - aiohttp-cors==0.7.0
    - aiorwlock==1.3.0
    - aiosignal==1.3.1
    - ansiwrap==0.8.4
    - apache-beam==2.43.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - babel==2.11.0
    - backoff==1.10.0
    - beatrix-jupyterlab==2022.128.30523
    - blessed==1.19.1
    - cachetools==5.2.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloud-tpu-client==0.10
    - cloud-tpu-profiler==2.4.0
    - cloudpickle==2.2.0
    - cmake==3.25.0
    - colorama==0.4.6
    - colorful==0.5.5
    - commonmark==0.9.1
    - crcmod==1.7
    - cycler==0.11.0
    - db-dtypes==1.0.5
    - debugpy==1.6.4
    - dill==0.3.1.1
    - distlib==0.3.6
    - dm-tree==0.1.7
    - docker==6.0.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - etils==0.9.0
    - explainable-ai-sdk==1.3.3
    - explainers==0.1
    - fastapi==0.88.0
    - fastavro==1.7.0
    - fasteners==0.18
    - filelock==3.8.2
    - flatbuffers==1.12
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gast==0.4.0
    - gcsfs==2022.11.0
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-api-core==1.34.0
    - google-api-python-client==1.8.0
    - google-apitools==0.5.31
    - google-auth==2.15.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.8.0
    - google-cloud-bigquery==3.4.1
    - google-cloud-bigquery-storage==2.13.2
    - google-cloud-bigtable==1.7.3
    - google-cloud-core==2.3.2
    - google-cloud-datastore==1.15.5
    - google-cloud-dlp==3.9.2
    - google-cloud-language==1.3.2
    - google-cloud-pubsub==2.13.11
    - google-cloud-pubsublite==1.6.0
    - google-cloud-recommendations-ai==0.7.1
    - google-cloud-spanner==3.26.0
    - google-cloud-storage==2.7.0
    - google-cloud-videointelligence==1.16.3
    - google-cloud-vision==1.0.2
    - google-crc32c==1.5.0
    - google-pasta==0.2.0
    - google-resumable-media==2.4.0
    - googleapis-common-protos==1.57.0
    - gpustat==1.0.0
    - greenlet==2.0.1
    - grpc-google-iam-v1==0.12.4
    - grpcio==1.51.1
    - grpcio-status==1.48.2
    - gviz-api==1.10.0
    - gym==0.23.1
    - gym-notices==0.0.8
    - h11==0.14.0
    - h5py==3.7.0
    - hdfs==2.7.0
    - htmlmin==0.1.12
    - httplib2==0.21.0
    - imagehash==4.3.1
    - imageio==2.22.4
    - importlib-metadata==5.1.0
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipython-sql==0.4.1
    - ipywidgets==8.0.3
    - joblib==1.2.0
    - json5==0.9.10
    - jupyter-core==4.12.0
    - jupyter-http-over-ws==0.0.8
    - jupyter-server-mathjax==0.2.6
    - jupyter-server-proxy==3.2.2
    - jupyterlab==3.4.8
    - jupyterlab-git==0.41.0
    - jupyterlab-server==2.16.5
    - jupyterlab-widgets==3.0.4
    - jupytext==1.14.4
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - keras-tuner==1.1.3
    - kiwisolver==1.4.4
    - kt-legacy==1.0.4
    - kubernetes==25.3.0
    - libclang==14.0.6
    - llvmlite==0.39.1
    - markdown==3.4.1
    - markdown-it-py==2.1.0
    - markupsafe==2.0.1
    - matplotlib==3.5.3
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - msgpack==1.0.4
    - multidict==6.0.3
    - multimethod==1.9
    - nbclient==0.7.2
    - nbdime==3.1.1
    - networkx==2.6.3
    - notebook-executor==0.2
    - numba==0.56.4
    - numpy==1.21.6
    - nvidia-ml-py==11.495.46
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - objsize==0.5.2
    - opencensus==0.11.0
    - opencensus-context==0.1.3
    - opentelemetry-api==1.1.0
    - opentelemetry-exporter-otlp==1.1.0
    - opentelemetry-exporter-otlp-proto-grpc==1.1.0
    - opentelemetry-proto==1.1.0
    - opentelemetry-sdk==1.1.0
    - opentelemetry-semantic-conventions==0.20b0
    - opt-einsum==3.3.0
    - orjson==3.8.3
    - overrides==6.5.0
    - packaging==21.3
    - pandas==1.3.5
    - pandas-profiling==3.5.0
    - papermill==2.4.0
    - pathtools==0.1.2
    - patsy==0.5.3
    - phik==0.12.3
    - pillow==9.3.0
    - platformdirs==2.6.0
    - plotly==5.11.0
    - prettytable==0.7.2
    - prometheus-client==0.13.1
    - promise==2.3
    - proto-plus==1.22.1
    - protobuf==3.19.6
    - py-spy==0.3.14
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pydot==1.4.2
    - pyjwt==2.6.0
    - pymongo==3.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - pytz==2022.6
    - pywavelets==1.3.0
    - pyyaml==6.0
    - rasterio==1.2.10
    - ray==2.2.0
    - ray-cpp==2.2.0
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rich==12.6.0
    - rsa==4.7.2
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.1
    - sentry-sdk==1.13.0
    - setproctitle==1.3.2
    - simpervisor==0.4
    - smart-open==6.3.0
    - smmap==5.0.0
    - snuggs==1.4.7
    - sqlalchemy==1.4.45
    - sqlparse==0.4.3
    - starlette==0.22.0
    - statsmodels==0.13.5
    - tabulate==0.9.0
    - tangled-up-in-unicode==0.2.0
    - tenacity==8.1.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-profile==2.11.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.9.3
    - tensorflow-cloud==0.1.16
    - tensorflow-datasets==4.7.0
    - tensorflow-estimator==2.9.0
    - tensorflow-hub==0.12.0
    - tensorflow-io==0.28.0
    - tensorflow-io-gcs-filesystem==0.28.0
    - tensorflow-metadata==1.10.0
    - tensorflow-probability==0.19.0
    - tensorflow-serving-api==2.9.3
    - tensorflow-transform==1.10.1
    - termcolor==2.1.1
    - textwrap3==0.9.2
    - tfx-bsl==1.10.1
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - toml==0.10.2
    - tomli==2.0.1
    - tqdm==4.64.1
    - typeguard==2.13.3
    - typer==0.7.0
    - uritemplate==3.0.1
    - uvicorn==0.20.0
    - virtualenv==20.17.1
    - visions==0.7.5
    - wandb==0.13.9
    - webencodings==0.5.1
    - werkzeug==2.1.2
    - widgetsnbextension==4.0.4
    - witwidget==1.8.1
    - wrapt==1.14.1
    - yarl==1.8.2
prefix: /opt/conda
